"""Add otp_code and otp_expires_at to owners table

Revision ID: 2566b94b90c5
Revises: 95823198c031
Create Date: 2025-09-16 11:33:41.219281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2566b94b90c5'
down_revision: Union[str, Sequence[str], None] = '95823198c031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('store_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('customers_ibfk_1'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'stores', ['store_id'], ['id'])
    op.drop_column('customers', 'owner_id')
    op.add_column('orders', sa.Column('store_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('orders_ibfk_1'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'stores', ['store_id'], ['id'])
    op.drop_column('orders', 'owner_id')
    op.add_column('owners', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('owners', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'otp_expires_at')
    op.drop_column('owners', 'otp_code')
    op.add_column('orders', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'owners', ['owner_id'], ['id'])
    op.drop_column('orders', 'store_id')
    op.add_column('customers', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_ibfk_1'), 'customers', 'owners', ['owner_id'], ['id'])
    op.drop_column('customers', 'store_id')
    # ### end Alembic commands ###
